backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "/img"

locale: "ru"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "site/content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Страницы"
    files:
      - file: "site/content/how-to/_index.md"
        label: "Инструкции"
        name: "how-to"
        fields:
          - {label: Title, name: title, widget: string}
          - {lavel: Content, name: content, widget: markdown}
      - file: "site/content/contact/_index.md"
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text
      - file: "site/content/next/_index.md"
        label: "Что дальше"
        name: "next"
        fields:
          - {label: Title, name: title, widget: string}
          - {lavel: Content, name: content, widget: markdown}
      - file: "site/content/values/_index.md"
        label: "Values Page"
        name: "values"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - label: Values
            name: values
            widget: list
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Text, name: text, widget: text}
              - {label: Image, name: imageUrl, widget: image}
  - name: "news"
    label: "Новости"
    folder: "site/content/news"
    create: true
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - { name: "date", label: "Дата публикации", widget: "datetime" }
      - { name: "description", label: "Краткое описание", widget: "text" }
      - { name: "image", label: "Фото", widget: "image", required: false}
      - { name: "body", label: "Текст", widget: "markdown"}
  - name: "maps"
    label: "Карты"
    folder: "site/content/maps"
    create: true
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - name: "courses"
        label: "Дистанции"
        widget: "list"
        fields:
          - label: "Сложность"
            name: "difficalty"
            widget: "string"
          - label: "Описание"
            name: "description"
            widget: "markdown"
          - label: "Карта с дистанцией"
            name: "file"
            widget: "file"
